---
- name: Ensure docker is installed.
  ansible.builtin.include_role:
    name: geerlingguy.docker
  vars:
    docker_edition: "{{ bsd_docker_edition }}"
    docker_package: "docker-{{ bsd_docker_edition }}"
    docker_package_state: present
    docker_install_compose: true